language: node_js
node_js:
  - '8'
os: linux
before_script:
  - npm install -g pm2
install:
  - npm install
dist: trusty
<<<<<<< HEAD
sudo: false
=======
sudo: false
>>>>>>> edacdda7438983cfb3ac0796488c63b74af6535d
